import { defaultThemeColors } from './defaultThemeColors';

// Note - Typing is generated by this constant
export const defaultButtonVariants = {
  primary: {
    backgroundColor: defaultThemeColors.primary,
    color: defaultThemeColors.white,
    '&:hover': {
      backgroundColor: defaultThemeColors.primaryLight,
    },
    '&:active': {
      backgroundColor: defaultThemeColors.primaryDark,
    },
    '&:disabled': {
      backgroundColor: defaultThemeColors.primaryLightest,
    },
  },
  primaryText: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    color: defaultThemeColors.primary,
    '&:hover': {
      color: defaultThemeColors.primaryDark,
    },
  },
  secondary: {
    backgroundColor: 'transparent',
    borderColor: defaultThemeColors.primary,
    color: defaultThemeColors.primary,
    '&:hover': {
      backgroundColor: defaultThemeColors.primary,
      color: defaultThemeColors.white,
    },
    '&:active': {
      backgroundColor: defaultThemeColors.primaryDark,
      color: defaultThemeColors.white,
    },
    '&:disabled': {
      borderColor: defaultThemeColors.primaryLightest,
      color: defaultThemeColors.primaryLightest,
    },
  },
  grey: {
    backgroundColor: defaultThemeColors.white,
    borderColor: defaultThemeColors.grey,
    color: defaultThemeColors.greyDarkest,
    '&:hover': {
      borderColor: defaultThemeColors.greyDark,
    },
    '&:active': {
      backgroundColor: defaultThemeColors.greyLight,
    },
    '&:disabled': {
      borderColor: defaultThemeColors.grey,
      color: defaultThemeColors.grey,
    },
  },
  greyText: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    color: defaultThemeColors.grey,
    '&:hover': {
      color: defaultThemeColors.greyDark,
    },
  },
  success: {
    color: defaultThemeColors.white,
    backgroundColor: defaultThemeColors.secondary,
    '&:hover': {
      backgroundColor: defaultThemeColors.secondaryLight,
    },
    '&:active': {
      backgroundColor: defaultThemeColors.secondaryDark,
    },
    '&:disabled': {
      backgroundColor: defaultThemeColors.secondaryLightest,
    },
  },
  warning: {
    backgroundColor: defaultThemeColors.orange,
    color: defaultThemeColors.white,
    '&:hover': {
      backgroundColor: defaultThemeColors.orangeLight,
    },
    '&:active': {
      backgroundColor: defaultThemeColors.orangeDark,
    },
    '&:disabled': {
      backgroundColor: defaultThemeColors.orangeLightest,
    },
  },
  danger: {
    backgroundColor: defaultThemeColors.red,
    color: defaultThemeColors.white,
    '&:hover': {
      backgroundColor: defaultThemeColors.redLight,
    },
    '&:active': {
      backgroundColor: defaultThemeColors.redDark,
    },
    '&:disabled': {
      backgroundColor: defaultThemeColors.redLightest,
    },
  },
  info: {
    backgroundColor: defaultThemeColors.blue,
    color: defaultThemeColors.white,
  },
} as const;
